import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LayoutClient from "./LayoutClient";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <LayoutClient>{children}</LayoutClient>
        </body>
      </html>
    </ClerkProvider>
  );
}
